# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created: Sat Mar 14 00:18:09 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_WebShutter(object):
    def setupUi(self, WebShutter):
        WebShutter.setObjectName("WebShutter")
        WebShutter.resize(566, 603)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        WebShutter.setFont(font)
        WebShutter.setStyleSheet("background-color: rgb(215, 241, 255);")
        self.centralwidget = QtGui.QWidget(WebShutter)
        self.centralwidget.setObjectName("centralwidget")
        self.textbox_url = QtGui.QTextEdit(self.centralwidget)
        self.textbox_url.setGeometry(QtCore.QRect(50, 10, 421, 21))
        self.textbox_url.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_url.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_url.setObjectName("textbox_url")
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(480, 10, 71, 21))
        self.btn_add.setStyleSheet("border-color: rgb(125, 134, 255);\n"
"background-color: rgb(179, 189, 255);")
        self.btn_add.setObjectName("btn_add")
        self.label_urls = QtGui.QLabel(self.centralwidget)
        self.label_urls.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_urls.setFont(font)
        self.label_urls.setObjectName("label_urls")
        self.groupBox_other = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_other.setGeometry(QtCore.QRect(10, 40, 541, 131))
        self.groupBox_other.setStyleSheet("border-color: rgb(201, 199, 255);")
        self.groupBox_other.setObjectName("groupBox_other")
        self.groupBox = QtGui.QGroupBox(self.groupBox_other)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 141, 51))
        self.groupBox.setObjectName("groupBox")
        self.radio_mobile = QtGui.QRadioButton(self.groupBox)
        self.radio_mobile.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.radio_mobile.setObjectName("radio_mobile")
        self.radio_desktop = QtGui.QRadioButton(self.groupBox)
        self.radio_desktop.setGeometry(QtCore.QRect(70, 20, 61, 17))
        self.radio_desktop.setChecked(True)
        self.radio_desktop.setObjectName("radio_desktop")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_other)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 60, 141, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textbox_height = QtGui.QPlainTextEdit(self.groupBox_2)
        self.textbox_height.setGeometry(QtCore.QRect(90, 20, 41, 21))
        self.textbox_height.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_height.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_height.setObjectName("textbox_height")
        self.textbox_width = QtGui.QPlainTextEdit(self.groupBox_2)
        self.textbox_width.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.textbox_width.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_width.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_width.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_width.setObjectName("textbox_width")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(64, 20, 16, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textbox_output_dir = QtGui.QPlainTextEdit(self.groupBox_other)
        self.textbox_output_dir.setEnabled(True)
        self.textbox_output_dir.setGeometry(QtCore.QRect(82, 20, 211, 21))
        self.textbox_output_dir.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_output_dir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_output_dir.setObjectName("textbox_output_dir")
        self.btn_browse = QtGui.QPushButton(self.groupBox_other)
        self.btn_browse.setGeometry(QtCore.QRect(299, 19, 75, 23))
        self.btn_browse.setStyleSheet("border-color: rgb(125, 134, 255);\n"
"background-color: rgb(179, 189, 255);")
        self.btn_browse.setObjectName("btn_browse")
        self.textbox_output_sub_dir = QtGui.QPlainTextEdit(self.groupBox_other)
        self.textbox_output_sub_dir.setGeometry(QtCore.QRect(440, 20, 91, 21))
        self.textbox_output_sub_dir.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_output_sub_dir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_output_sub_dir.setObjectName("textbox_output_sub_dir")
        self.label_2 = QtGui.QLabel(self.groupBox_other)
        self.label_2.setGeometry(QtCore.QRect(385, 22, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtGui.QLabel(self.groupBox_other)
        self.label_4.setGeometry(QtCore.QRect(10, 22, 71, 16))
        self.label_4.setObjectName("label_4")
        self.table_urls = QtGui.QTableWidget(self.centralwidget)
        self.table_urls.setGeometry(QtCore.QRect(10, 200, 541, 361))
        self.table_urls.setFrameShape(QtGui.QFrame.StyledPanel)
        self.table_urls.setFrameShadow(QtGui.QFrame.Sunken)
        self.table_urls.setAlternatingRowColors(True)
        self.table_urls.setObjectName("table_urls")
        self.table_urls.setColumnCount(4)
        self.table_urls.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_urls.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_urls.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_urls.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_urls.setHorizontalHeaderItem(3, item)
        self.table_urls.verticalHeader().setSortIndicatorShown(False)
        self.table_urls.verticalHeader().setStretchLastSection(False)
        self.btn_start = QtGui.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(498, 175, 50, 21))
        self.btn_start.setStyleSheet("border-color: rgb(125, 134, 255);\n"
"background-color: rgb(26, 255, 121);")
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtGui.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(440, 175, 50, 21))
        self.btn_stop.setStyleSheet("border-color: rgb(125, 134, 255);\n"
"background-color: rgb(232, 33, 47);")
        self.btn_stop.setObjectName("btn_stop")
        self.btn_search = QtGui.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(307, 174, 21, 21))
        self.btn_search.setStyleSheet("border-color: rgb(213, 213, 213);\n"
"background-color: rgb(250, 253, 254);")
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        self.textbox_search = QtGui.QPlainTextEdit(self.centralwidget)
        self.textbox_search.setEnabled(True)
        self.textbox_search.setGeometry(QtCore.QRect(93, 174, 211, 21))
        self.textbox_search.setStyleSheet("background-color: rgb(249, 255, 176);")
        self.textbox_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textbox_search.setObjectName("textbox_search")
        self.comboBox_search = QtGui.QComboBox(self.centralwidget)
        self.comboBox_search.setGeometry(QtCore.QRect(10, 174, 81, 22))
        self.comboBox_search.setStyleSheet("background-color: rgb(249, 255, 176);\n"
"border-color: rgb(214, 214, 214);")
        self.comboBox_search.setObjectName("comboBox_search")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.comboBox_search.addItem("")
        self.btn_delete = QtGui.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(381, 175, 50, 21))
        self.btn_delete.setStyleSheet("border-color: rgb(125, 134, 255);\n"
"background-color: rgb(241, 146, 50);")
        self.btn_delete.setObjectName("btn_delete")
        WebShutter.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(WebShutter)
        self.statusbar.setObjectName("statusbar")
        WebShutter.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(WebShutter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        self.menubar.setObjectName("menubar")
        WebShutter.setMenuBar(self.menubar)

        self.retranslateUi(WebShutter)
        QtCore.QMetaObject.connectSlotsByName(WebShutter)

    def retranslateUi(self, WebShutter):
        WebShutter.setWindowTitle(QtGui.QApplication.translate("WebShutter", "Web Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("WebShutter", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_urls.setText(QtGui.QApplication.translate("WebShutter", "URL/s", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_other.setTitle(QtGui.QApplication.translate("WebShutter", "Other Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("WebShutter", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_mobile.setText(QtGui.QApplication.translate("WebShutter", "Mobile", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_desktop.setText(QtGui.QApplication.translate("WebShutter", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("WebShutter", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.textbox_height.setPlainText(QtGui.QApplication.translate("WebShutter", "960", None, QtGui.QApplication.UnicodeUTF8))
        self.textbox_width.setPlainText(QtGui.QApplication.translate("WebShutter", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WebShutter", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_browse.setText(QtGui.QApplication.translate("WebShutter", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WebShutter", "Sub Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WebShutter", "Output Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.table_urls.setSortingEnabled(False)
        self.table_urls.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("WebShutter", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.table_urls.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("WebShutter", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.table_urls.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("WebShutter", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("WebShutter", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop.setText(QtGui.QApplication.translate("WebShutter", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_search.setItemText(0, QtGui.QApplication.translate("WebShutter", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_search.setItemText(1, QtGui.QApplication.translate("WebShutter", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_search.setItemText(2, QtGui.QApplication.translate("WebShutter", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_search.setItemText(3, QtGui.QApplication.translate("WebShutter", "Checked", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_search.setItemText(4, QtGui.QApplication.translate("WebShutter", "Unchecked", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete.setText(QtGui.QApplication.translate("WebShutter", "Delete", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WebShutter = QtGui.QMainWindow()
    ui = Ui_WebShutter()
    ui.setupUi(WebShutter)
    WebShutter.show()
    sys.exit(app.exec_())

